<?

 /* File Generated by phpfreaks.com - http://www.phpfreaks.com.
Please visit our site for quick code snipplets, tutorials and much more!

This file may require modification to work properly.
*/

// Title: Hit counter
// Author: LeoXavior 
// Date: December 17th, 2002


// Code Snipplet:
php
/*
######################################################################################
This is a simple hit counter creates/writes to file:::> counter.hits                 #
Set Vars uptop to the file you want to make and your start date.      		     #
-Updated so counter.hits only logs one instance of the same ip to keep filesize down #
######################################################################################
*/
/*
Core Variables
*/
$filename = "logs/counter.hits" ;
$startdate = "January 2005" ;
$ip = getenv("REMOTE_ADDR") ;
$currentip = "$ip"; 
$file = file($filename);
$file = array_unique($file);


/*
This is the guts of the counter
*/   
$file = "$filename"; 
$fd = fopen ($file, "r"); 
$fget= fread ($fd, filesize ($file)); 
fclose ($fd); 
$totalips = htmlspecialchars($fget); 
if (preg_match ("/$ip/i", "$totalips")) 
{$file = file($filename);
$file = array_unique($file);
$hits = count($file);
echo "Visitors since,<br>";
echo "$startdate: 000$hits";}  
else 
{ 
$fd = fopen ($filename , "r");
$fstring = fread ($fd , filesize ($filename)) ;
fclose($fd) ;
$fd = fopen ($filename , "w");
$fcounted = $fstring.$currentip."\n";
$fout= fwrite ($fd , $fcounted);
fclose($fd);
$file = file($filename);
$file = array_unique($file);
$hits = count($file);
echo "Visitors since,<br>";
echo "$startdate: 000$hits";
} 

 

/* Description:

This counter logs ips of ppl that hit your site, and unlike alot of similar counters it checks if the ip is already listed and skips re-adding it to keep filesize down.. Was a must do for me just fixed it 
- Dec. 2002
*/

?>